### ISSUE TITLE
asset-scanner example not getting descriptions

### ISSUE THREAD

**Issue by Mahir-Sparkess** [cedadev/asset-scanner#17]
The asset scanner example returns an empty description, the root_directory attribute does point to the correct location. printing `description.__dict__` in the `item_generator.facet_extractor` shows an empty `_descriptions: {}` even though the yaml description is filled.

**Comment by Mahir-Sparkess** [comment]
I should also note that I was running an older version for the asset_scanner that did return the descriptions with my out-of-date fork.

**Comment by rsmith013** [comment]
This is resolved
